Repository PPiing/backend, pull requests merged in 2022-08, with the labels that each got.

#185 게임초대를 위해서 게임생성부분을 분리했습니다.
  .eslintrc.json
  src/game/dto/game-session.dto.ts
  src/game/game.gateway.ts
  src/game/game.service.ts
Labels: game

#188 :fix: friend list err fix #187
  src/entities/friends.entity.ts
  src/user/repository/user.repository.ts
  src/user/user.service.ts
Labels: SKIM

#199 :passport_control: 2FA error fix #197
  src/auth/auth.controller.ts
Labels: bug, SKIM

#200 :bug: block error fix #198
  src/community-bar/friends/friends.controller.ts
Labels: bug, SKIM

#203 :bug: friends reaction err fix #201
  src/community-bar/friends/friends.controller.ts
  src/community-bar/friends/repository/friends.repository.ts
Labels: bug, SKIM

#210 :bug: friend accept err fix #201
  src/community-bar/friends/repository/friends.repository.ts
Labels: bug, SKIM

#219 Feat #218 (사실 skim) 🎸
  src/community-bar/friends/friends.controller.ts
  src/community-bar/friends/friends.module.ts
  src/entities/chat-event.entity.ts
  src/entities/game-log.entity.ts
  src/entities/profile.entity.ts
  src/entities/user-achiv.entity.ts
  src/status/status.gateway.ts
  src/status/status.service.ts
Labels: bug, SKIM, refac

#221 feat: ball bound paddle with radian base
  src/configs/configuration.ts
  src/game/calPosition/calculate.ball.velocity.ts
  src/game/checkBound/check.paddle.bound.ts
  src/game/dto/in-game.dto.ts
  src/game/dto/spec.dto.ts
  src/game/game.controller.ts
  src/game/gameStatus/playing.ts
Labels: game, JINBAE

#243 await update game result
  src/game/game-log.service.ts
Labels: game, JINBAE

#246 Feat #245
  src/community-bar/friends/friends.controller.ts
  src/community-bar/friends/friends.gateway.ts
  src/community-bar/friends/friends.service.ts
  src/community-bar/friends/repository/friends.repository.ts
Labels: bug, enhancement, SKIM

#269 Feat #263
  src/community-bar/friends/friends.service.ts
  src/community-bar/friends/repository/friends.repository.ts
Labels: bug, SKIM
