Repository PPiing/backend, pull requests merged in 2022-07, with the labels that each got.

#121 :bug: profile dto swagger 수정 #113
  src/profile/dto/get-profile.dto.ts
Labels: bug, SKIM

#125 :art: friend logic update #124
  src/alarm/alarm.module.e2e-spec.ts
  src/alarm/alarm.module.ts
  src/app.module.e2e-spec.ts
  src/community-bar/friends/friends.controller.ts
  src/community-bar/friends/friends.gateway.ts
  src/community-bar/friends/friends.module.e2e-spec.ts
  src/community-bar/friends/friends.module.ts
  src/community-bar/friends/friends.service.ts
  src/game/game-socket-session.ts
  src/profile/profile.module.e2e-spec.ts
Labels: enhancement, SKIM

#130 fix: import check func directly, #127
  src/game/simulation.service.ts
Labels: refac

#132 Feat/game/wallcollision
  src/game/calCollision/wall.collision.ts
  src/game/simulation.service.ts
Labels: refac

#134 fix: handler direction
  src/game/handler/paddle.ts
  src/game/simulation.service.ts
Labels: bug, refac

#157 Feat #154
  src/auth/auth.controller.ts
  src/community-bar/friends/friends.controller.ts
  src/community-bar/friends/friends.module.e2e-spec.ts
  src/community-bar/friends/friends.module.ts
  src/community-bar/friends/friends.service.ts
  src/community-bar/friends/repository/friends.repository.ts
  src/community-bar/friends/repository/mock/mock.friends.repository.ts
  src/enums/profile-relation.enum.ts
  src/profile/dto/get-profile.dto.ts
  src/profile/profile.controller.ts
  src/profile/profile.module.e2e-spec.ts
  src/profile/profile.module.ts
  test/user.e2e-spec.ts
Labels: enhancement, SKIM

#159 :bug: logout error fix #153
  src/auth/auth.controller.ts
Labels: bug, SKIM

#177 fix: custom session to express session
  src/auth/ft.strategy.ts
  src/game/dto/game-session.dto.ts
  src/game/game-log.service.spec.ts
  src/game/game-socket-session.ts
  src/game/game.gateway.ts
  src/game/game.module.e2e-spec.ts
  src/game/game.module.ts
  src/game/repository/game-log.repository.ts
  src/user/dto/user.dto.ts
  src/user/repository/user.repository.ts
  src/user/user.service.ts
Labels: help wanted, game
